# Configuration file for the Sphinx documentation builder.

import os
import sys
import sphinx_rtd_theme

# -- Project information -----------------------------------------------------
project = 'BD Forge (Data Hopper)'
copyright = '2026, YirehStudios'
author = 'YirehStudios'
release = 'vE 2.0.0.0'

# -- General configuration ---------------------------------------------------
extensions = [
    'sphinx_rtd_theme',
]

templates_path = ['_templates']
exclude_patterns = ['_build', 'Thumbs.db', '.DS_Store']

# -- Internationalization (i18n) ---------------------------------------------
# The language for content autogenerated by Sphinx. 
# We set English as the source language.
language = 'en'

# Paths for translation files (.po/.mo)
locale_dirs = ['locale/'] 
gettext_compact = False 

# -- Options for HTML output -------------------------------------------------
html_theme = 'sphinx_rtd_theme'
html_static_path = ['_static']

# Theme options to show language selector (if implemented in theme)
html_context = {
    'display_github': False,
    'last_updated': True,
    'commit': False,
}